### ISSUE TITLE
Add DSL verb for `upload`.

### ISSUE THREAD

**Issue by holetse** [labzero/bootleg#140]
Uploading a file to the remote host can be done by using `Bootleg.SSH.upload/3`, but its usage is undocumented and it requires a raw `SSHKit.Context`. Exposing this functionality via the DSL with proper role/host support is a much better alternative.

```elixir
use Bootleg.Config

after_task :deploy do
  # dumps to the remote workspace
  upload :app, "path/to/a/local/file"

  # or with an explicit destination
  upload :app, "path/to/a/local/file", "remote/path"
end
```

**Comment by rjanja** [comment]
Closed via #149
