### ISSUE TITLE
bootleg.build doesn't start with a clean workspace

### ISSUE THREAD

**Issue by rjanja** [labzero/bootleg#142]
This was recently observed when phoenix asset digest failed but its error didn't cause the build to be aborted. The assets appeared to still have been bundled into and deployed with the app, but were actually old assets from a previous build.

To repro:
* On build host, `echo "foo" > /tmp/bootleg/build/priv/static/bar` (using your build workspace)
* Run `mix bootleg.update`
* On app server, `file /opt/app/lib/app-0.0.1/priv/static/bar` (using your app name and version)

Expected: "bar: No such file or directory"
Occurred: "bar: ASCII text"

**Comment by holetse** [comment]
I am in favor of blindly nuking the workspace before building (with an option to suppress), but it would be good to get other opinions. The recompile/refetch of dependencies that might occur seems like the biggest drawback to that approach. In the interest of simplicity and ease of use, I'd rather refetch/recompile dependencies then spend hours tracking down a subtle "stale asset" bug.

Another option I see is to have a list of places to clean relative to the workspace, so a user (or package like `bootleg_phoenix`) can specify what they want cleaned. Maybe that would default to `["."]`?

**Comment by rjanja** [comment]
+1 for blindly nuking the workspace for now.

I do like the option you've proposed and would love to see it split off into another issue.
