### ISSUE TITLE
bootleg.update doesn't restart a running app

### ISSUE THREAD

**Issue by rjanja** [labzero/bootleg#143]
```
task :update do
  invoke :build
  invoke :deploy
  invoke :start
end
```

If the app is already running, Distillery `start` will not stop it and start it again on its own.

Unlike `restart`, Distillery's `start` and `stop` will not throw errors if the running status is unexpected, so it's possible we can just add an `invoke :stop` in our `:update` task to fix the problem, but this may require some more work.

**Comment by holetse** [comment]
Calling `stop` and then `start` seems reasonable to me. I think we will need to add a delay/poll, as I believe `stop` in distillery operates asynchronously (I know start does). Maybe the best path is to make the bootleg versions of both `start` and `stop` handle the asynchronous nature?

**Comment by rjanja** [comment]
I think it's only `start` which operates asynchronously. `stop` seems to wait for the process to be completely poofed, so `stop` and then `start` should work fine for now I think.
https://github.com/bitwalker/distillery/blob/master/priv/libexec/commands/stop.sh

**Comment by holetse** [comment]
Hmm, `stop` does throw an error if the app is not already running, since `pid` does. I'm exploring other mechanisms to detect this case before I just suppress the error.

**Comment by rjanja** [comment]
Ah, you're right. I wasn't checking the exit status.

I think it's probably safer to assume that `update` is being used to update a running application than a stopped one. But I think it may be better to clarify what the command does and when it should be used than to suppress errors in it.

**Comment by rjanja** [comment]
Or, `update` could just not bother with attempting to start/restart the app, and instead that could be left to the user or implemented in a later PR

**Comment by holetse** [comment]
I like the idea of `update` doing the app start/restart. Needing to know the state of each and every node prior to doing a deploy seems like an unfair burden for the user.

By suppressing the error, I actually meant generate an "error" in such a way that its clear that node is not running the app. There doesn't seem to be any way in distillery to get the status of an app w/o generating some sort of error in the case where its not running.
