### ISSUE TITLE
Bundled tasks should use config DSL

### ISSUE THREAD

**Issue by rjanja** [labzero/bootleg#144]
Right now `:generate_release` and `:compile` are the only bundled tasks that use the config agent, but they should use it via the `config/0` macro.

```
# messy
config()[:mix_env] || "prod"
# better
Keyword.get(config(), :mix_env, "prod")
# ideal
# ...[future]
```

**Comment by holetse** [comment]
Agreed that using `config/0` would be an improvement here.

I like the idea of exposing something with the same semantics as `get_config/2` in the DSL. Specifically, gets a key from the current config in the agent, and provides an optional default if the key is undefined. I don't have a good idea of what to call it though. `get_config` would work, but doesn't feel like a great fit with the rest of the nomenclature. `config/1` that just took a key and didn't do the default value is another option that comes to mind. Defaulting would still need to be done by the caller though, `config(:mix_env) || "prod"`.

**Comment by holetse** [comment]
Could do something like `config/1` with `config :mix_env`, `config [:mix_env, :prod]` and/or `config [:mix_env, default: :prod]`.

**Comment by rjanja** [comment]
It could just be me but any more arity than `config/1` makes it read like it's setting something.
What do you think of using `get/0` and `get/1` instead?

**Comment by holetse** [comment]
I went with `config/1`, with the option of providing a default via a tuple.
