### ISSUE TITLE
SSHKit internal error when using identity file with passphrase

### ISSUE THREAD

**Issue by mintcore** [labzero/bootleg#156]
I've been trying to get bootleg to work for a while now but seem to be completely stuck on even getting commands to run on the server. Anyone having a clue what is wrong? 

I can ssh into the remote server the regular way without issues so that rules out the any problem with the key.

My config:
```
role :build, "my-domain.com",
  user: "deploy",
  identity: Path.expand("~/.ssh/id_rsa"),
  workspace: "~/tmp/bootleg/build"
```

Stacktrace from `mix bootleg.build production` (using elixir 1.5.1 and OTP 20)
```
Creating remote context at '~/tmp/bootleg/build'
[my-domain.com] /usr/bin/env mkdir -p ~/tmp/bootleg/build
** (SSHError) SSHKit returned an internal error on my-domain.com: {:function_clause, [{:public_key, :pem_entry_decode, [{:RSAPrivateKey, <<191, 8, 24, 153, 216, 76, 147, 2, 19, 72, 42, 182, 142, 174, 157, 112, 161, 94, 6, 160, 222, 224, 247, 247, 52, 200, 16, 19, 244, 44, 128, 219, 71, 131, 153, 55, 179, 128, 124, 232, 217, 140, 10, ...>>, {'AES-128-CBC', <<84, 47, 220, 211, 67, 173, 224, 77, 235, 222, 244, 234, 184, 159, 23, 18>>}}], [file: 'public_key.erl', line: 131]}, {SSHClientKeyAPI, :user_key, 2, [file: 'lib/ssh_client_key_api.ex', line: 102]}, {:ssh_auth, :get_public_key, 2, [file: 'ssh_auth.erl', line: 145]}, {:ssh_connection_handler, :is_usable_user_pubkey, 2, [file: 'ssh_connection_handler.erl', line: 1744]}, {:ssh_connection_handler, :"-init_ssh_record/4-lc$^0/1-0-", 2, [file: 'ssh_connection_handler.erl', line: 467]}, {:ssh_connection_handler, :init_ssh_record, 4, [file: 'ssh_connection_handler.erl', line: 466]}, {:ssh_connection_handler, :init, 1, [file: 'ssh_connection_handler.erl', line: 401]}, {:ssh_connection_handler, :init_connection_handler, 3, [file: 'ssh_connection_handler.erl', line: 364]}]}
    lib/bootleg/ssh.ex:66: anonymous fn/2 in Bootleg.SSH.run/2
    (elixir) lib/enum.ex:1255: Enum."-map/2-lists^map/1-0-"/2
    lib/bootleg/ssh.ex:109: Bootleg.SSH.run!/2
    lib/bootleg/ssh.ex:83: Bootleg.SSH.validate_workspace/3
    lib/strategies/build/distillery.ex:9: Bootleg.Strategies.Build.Distillery.init/0
    lib/strategies/build/distillery.ex:16: Bootleg.Strategies.Build.Distillery.build/0
    lib/bootleg/config.ex:311: Bootleg.Config.invoke/1
    (mix) lib/mix/task.ex:301: Mix.Task.run_task/3
```

**Comment by svoynow** [comment]
It looks as if the underlying erlang :ssh library isn't liking your key. It is failing trying to decode it's contents. Are there any relevant details you can share about how that key was generated etc.? It's definitely something that *should* work, but the erlang :ssh library can have subtly different behavior than your standard unix `ssh` command line client.

**Comment by mintcore** [comment]
Thanks for the fast reply. It should be a pretty standard key. It's been generated on OSX with ssh-keygen. Not 100% sure about the passed params though. 

Maybe the easiest way is to generate a new one and try that? What do you think?

**Comment by mintcore** [comment]
Tried again with a newly generated key (`ssh-keygen -t rsa -b 4096 -C "your_email@example.com"`) and got the same issue.

**Comment by svoynow** [comment]
Puzzling. I just generated a key the same way and it seemed to work fine.

The only thing I can think of is if your key has a pass-phrase, since that's not supported.

**Comment by rjanja** [comment]
@mintcore was that the problem? If so we can close this.

I've opened labzero/ssh_client_key_api#3 for discussing how to handle the case where a passphrase-protected key has been supplied. This type of failure could probably stand to be a little more obvious.

**Comment by mintcore** [comment]
@rjanja Yes the key is passphrase-protected, although the passphrase has been added to keychain via `ssh-add -K`. Guess erlang hasn't got access to it somehow.

**Comment by rjanja** [comment]
Yeah, your guess is correct, there's no interaction with the keychain. Identity files are currently only supported when they have no passphrase set. This is something we should call out in the docs.
