### ISSUE TITLE
Task hook for symlinking prod.secret.exs

### ISSUE THREAD

**Issue by justincjohnson** [labzero/bootleg#160]
I would like to symlink my prod.secret.exs files from outside the git repo after git clone but before a build.  I was hoping there might be a git_clone task or something similar that I can create an after_task hook for.  Does that sound like a reasonable feature to add?  If there's a better way to handle secrets I'd love to hear.

Thanks, and I'm excited to see where the project leads.  :)

**Comment by rjanja** [comment]
Hi, thanks for the feedback! Although it's usually a bad practice to store production credentials on a build server, it's currently possible to hook into this spot in the build process by using a `before_task :compile`:

```elixir
before_task :compile do
  IO.puts "do the bad thing"
  #System.ln_s!("/path/to/not/secrets", "path/to/new/link")
end
```

This hook will be executed after the repository has been cleaned and the dependencies have been fetched. Eventually we hope to have other parts of the build process separated out into internal tasks that can also be hooked into or altogether overridden for custom behaviors. Hope this helps!

**Comment by justincjohnson** [comment]
That is helpful.  Thanks.

If you don't mind me asking, it sounds like you're saying from your perspective the default Phoenix approach of creating these prod.secret.exs files should be discouraged?  This seems reasonable to me.  I ask because the build pukes without uploading the files.

I started moving toward checking those files in but using System.get_env for the values now, which presumably I would just not set to anything secret on the build server.

**Comment by rjanja** [comment]
At least when using a build server, yes. If you're using a 12FA-style configuration your build server would need to be set up to have secrets for all the environments you're building for, which would mean potentially having a lot of different credentials all stored in one place.

There are alternatives and the community seems to be moving closer towards adopting a best practice here.

A colleague noted this article as consolidating a lot of the possible solutions:
  http://michal.muskala.eu/2017/07/30/configuring-elixir-libraries.html

Specific to Bootleg, we still have some relevant docs about the problems (and possible solutions) with using runtime configuration when employing a build server:
  https://github.com/labzero/bootleg/blob/master/USAGE.md

**Comment by justincjohnson** [comment]
Very helpful info.  Thanks much!
