### ISSUE TITLE
Suppress sshd banner text

### ISSUE THREAD

**Issue by justincjohnson** [labzero/bootleg#163]
Is it possible to suppress the banner text for ssh connections?  It produces a lot of noise in the output.  I was hoping perhaps `quiet_mode` or something can be passed to Erlang's [ssh client](http://erlang.org/doc/man/ssh.html), but I haven't spent much time researching.

**Comment by holetse** [comment]
Thanks for getting in touch!

Currently bootleg doesn't support ignoring the banner text for SSH connections, though if your banner text is configured to only show for connections with a TTY you won't get one. Many OSes do this by default, or can be configured to do so. Bootleg connections are created without a TTY. Many linux flavors support a `.hushlogin` to disable the banner for a given user account as well (https://debian-administration.org/article/546/Giving_yourself_a_quieter_SSH_login).

You could switch the whole tool into silent mode with `Application.put_env(:bootleg, :verbosity, :silent)`, though that would silence all output. `quiet_mode` is not on the list of supported SSH options, but it seems like a useful addition. We'll get that in for the `0.5.0` release.
