### ISSUE TITLE
Remove references to local builds in README.

### ISSUE THREAD

**Issue by StephaneRob** [labzero/bootleg#171]
According to the doc if the `:build` role is not set the release should be done locally. If I remove the `role :build,...` line in `config/deploy.exs`  I get `** (ArgumentError) You must supply a %Host{}, a %Role{} or a defined role_name.`

What is the correct way to do it?

**Comment by holetse** [comment]
Oops, good catch! That's some vestigial documentation, and local builds are not supported by `bootleg` any more. If you want to do a "local" build, you can configure your `build` role to connect to localhost via SSH.

I'm going to update this issue to address the documentation bug.

**Comment by StephaneRob** [comment]
Thx for the info.

**Comment by joshuataylor** [comment]
Local builds would be amazing, as you could do it on CI for example. You don't need to mess around with another build server just for CI.

**Comment by brienw** [comment]
@joshuataylor Yes, there is still a plan to add local builds into bootleg. I realized we don't have an issue filed for it in github yet (it was in our previous issue tracker), so i've filed one #193
