### ISSUE TITLE
Add option to Pull repository to Build server (vs. Push)

### ISSUE THREAD

**Issue by StephaneRob** [labzero/bootleg#175]
Do you plan to add the ability to build a release by pulling code from repository (github..) instead by pushing local code ? (both would be useful)

**Comment by holetse** [comment]
Yes! This is definitely something we want to add in the future.

Our main priority right now is working on the simplest use case, which is the local push, but adding remote pull will be coming. The biggest challenge we see with the remote pull is how to handle authentication as simply as possible. Most likely that will be done by imposing the requirement that the remote servers already have the authentication set up for their git provider. Which is to say bootleg would not help at all with the authentication between the remote build server and the remote git repository. Would that fit your use case?

**Comment by StephaneRob** [comment]
Yes, it would be great!
Maybe keep both by adding an args to `mix bootleg.build` to specify local/remote push/pull.

**Comment by brienw** [comment]
Fixed in #233
