### ISSUE TITLE
Weird characters for quotes, and one line split across multiple lines of output

### ISSUE THREAD

**Issue by balduncle** [labzero/bootleg#176]
After upgrading to bootleg 0.5.0 the format of the output looks like the following.  Notice the quotes look weird now.  Some output has lines split across multiple lines of output as well, which may have been a problem before.

```
[MY_IP_ADDRESS ] removed âdeps/postgrex/lib/postgrex/extensions/int4.exâ
[MY_IP_ADDRESS ] removed direct
[MY_IP_ADDRESS ] ory: âdeps/postgrex/lib/postgrex/extensionsâ
```

I don't get any errors though like I did previously.

**Comment by holetse** [comment]
Interesting. The changes in 0.5.0 were for us to pass the data along 100% unaltered, so it sounds like the remote server and the local machine are using different locales. Do you know which locales are involved? Especially the locale of the remote machine.

The extra line showing up is mostly related to how SSHKit (and the underlying erlang SSH library) pass back data in chunks. No effort is currently made by bootleg to buffer chunks, so a newline will show up at the end of a chunk boundary, even if its not the proper end of the line. That's definitely something we can work on addressing.

**Comment by rjanja** [comment]
Regarding the locale differences, there are at least a few ways to get around this:
* Allow per-role or per-host settings of SSH environment vars to (effected via SSHKit.env)
  * E.g. `SSHKit.env(%{"LANG" => "C", "LC_ALL" => "C"})`
* Reading `LANG` from Bootleg's environment and setting the remote locale to correspond
* Encourage users to use the same locale across environments or to prefixes commands with environment vars that set the locale e.g. `LANG=C LC_ALL=C`, `LANG=en_US.UTF-8` etc.
