### ISSUE TITLE
Copy if build server host is same as app server host

### ISSUE THREAD

**Issue by StephaneRob** [labzero/bootleg#177]
If build server host is the same as app server host, copy release from `:build` workspace to `:app` workspace instead of uploading release from local.

**Comment by holetse** [comment]
Thanks for the feature request. Is the issue with uploading the release back just that for a large release it's kind of slow? This seems like an optimization that we are unlikely to make, but I'd like to fully understand the need.

If there was a way to archive a release, deploy from that archive directly, and configure the archive to reside on an arbitrary server (in your case the single server), would that achieve your goals? It would be a network copy between localhost and localhost still.

**Comment by StephaneRob** [comment]
Sorry for the late reply. Yes actually it can be really slow to upload a release back to the build server (app server too). For now, I build the release on the server and manually copy the release and unpack it to app directory to bypass the deploy task.

**Comment by brienw** [comment]
Yes, I would definitely be interested in seeing it. We could perhaps come up with a config setting to enable it, aside from just checking to see if build and deploy are the same. I know in some of our use cases, we want to build, then pull that thing down to run acceptance tests on it before we then deploy the "blessed" release. But i think having the option to build and deploy all in one go with no interstitial download step will be of value to many people.

**Comment by brienw** [comment]
Added with [#216]
