### ISSUE TITLE
Phoenix 1.3 Support

### ISSUE THREAD

**Issue by Sathras** [labzero/bootleg#191]
I am having some issues getting the assets for phoenix 1.3 working:

this is the default phoenix task in my deploy.exs:

```
after_task :compile do
  mix_env = Keyword.get(config(), :mix_env, "prod")
  remote :build do
    "[ -f package.json ] && npm install || true"
    "[ -f brunch-config.js ] && [ -d node_modules ] && ./node_modules/brunch/bin/brunch b -p || true"
    "[ -d deps/phoenix ] && MIX_ENV=#{mix_env} mix phoenix.digest || true"
  end
end
```

I can successfully build, deploy and start the server, however, the priv/static directory will remain empty and no assets are built. I can see the server running but without assets. I assume this is because in Phoenix 1.3 the package.json is in the `/assets` directory. However adding `"cd ./assets"` directly after remote :build does fail.

Anyone has a clue? Thanks

**Comment by holetse** [comment]
Thanks for the report @Sathras! Using the [`cd` option](https://hexdocs.pm/bootleg/Bootleg.Config.html#remote/3) provided by `remote/3` should resolve your issue. You get the error because each line of a `remote` block is executed in a new shell currently, so the `cd` command does not impact subsequent calls.

Worth mentioning there is a [`bootleg_phoenix`](https://github.com/labzero/bootleg_phoenix) package which will provide support for Phoenix 1.3 shortly.

**Comment by Sathras** [comment]
thanks for the quick reply. I did try both variants and the result is the same. no assets / no errors.
i have tried it on a fresh vanilla phoenix 1.3 installation on ubuntu 16.04.

**Comment by Sathras** [comment]
I got it working, thanks for your help @holetse!
Here is the updated task for phoenix 1.3 applications:
```
after_task :compile do
  mix_env = Keyword.get(config(), :mix_env, "prod")
  
  remote :build, cd: "./assets" do
    "[ -f package.json ] && npm install || true"
    "[ -f brunch-config.js ] && [ -d node_modules ] && ./node_modules/brunch/bin/brunch b -p || true"
  end
  
  remote :build do
    "[ -d deps/phoenix ] && MIX_ENV=#{mix_env} mix phoenix.digest || true"
  end
end
```
Perhaps this should get merged into the next commit :)

**Comment by holetse** [comment]
Glad its working for you with the `cd` option!

I filed an issue (https://github.com/labzero/bootleg_phoenix/issues/9) to resolve the problem in `bootleg_phoenix`.

**Comment by holetse** [comment]
@Sathras `bootleg_phoenix` `0.2.0` is out, with your fix. Thanks!
