### ISSUE TITLE
Bootleg should allow for a local build option

### ISSUE THREAD

**Issue by brienw** [labzero/bootleg#193]
In the case that a user does not need to build on a remote host, bootleg should provide a way to run a build locally without the need to ssh.

**Comment by odarriba** [comment]
Any advance on this way? It would be awesome!

**Comment by brienw** [comment]
With @rjanja's recent changes to `task`ify the pipeline bits, this may actually be more realistically implementable than it was before. i'll take a fresh look

**Comment by brienw** [comment]
I want this to be reworked in #235
