### ISSUE TITLE
User interaction not allowed error

### ISSUE THREAD

**Issue by snewcomer** [labzero/bootleg#197]
When trying to build and deploy an application, I am getting the error below.  Since this lib uses sshkit under the hood, I was wondering if anybody has encountered the same problems and got around it?  Here is the related issue in sshkit.

Ref Issue: https://github.com/bitcrowd/sshkit.ex/issues/88

```
** (SSHError) SSHKit returned an internal error on 165.227.58.185: 'User interaction is not allowed'
    lib/bootleg/ssh.ex:70: anonymous fn/2 in Bootleg.SSH.run/2
    (elixir) lib/enum.ex:1255: Enum."-map/2-lists^map/1-0-"/2
    lib/bootleg/ssh.ex:163: Bootleg.SSH.run!/2
    lib/bootleg/ssh.ex:87: Bootleg.SSH.validate_workspace/3
    lib/bootleg/ssh.ex:51: Bootleg.SSH.init/2
    deps/bootleg/lib/bootleg/tasks/ping.exs:5: anonymous fn/3 in Bootleg.DynamicTasks.Ping.execute/0
    (elixir) lib/enum.ex:1811: Enum."-reduce/3-lists^foldl/2-0-"/3
    deps/bootleg/lib/bootleg/tasks/ping.exs:5: Bootleg.DynamicTasks.Ping.execute/0
```

**Comment by rjanja** [comment]
The 💣 is due to a failure to interact, I'm guessing either:

- An identity is being used and it's protected by passphrase
- The remote host fingerprint isn't known

Try adding `silently_accept_hosts: true` to the options. If that doesn't work, please share your `deploy.exs` with us. Thanks!

**Comment by snewcomer** [comment]
Ah `silently_accept_hosts` works.  Thank you!

**Comment by rjanja** [comment]
Great! 👍  Thanks for the feedback!
