### ISSUE TITLE
Invoke custom task failure

### ISSUE THREAD

**Issue by Virviil** [labzero/bootleg#200]
I'm trying to start run custom task via `mix bootleg.invoke` and getting nothing. So, this is the strategy:

1. I have the file in my projects lib, as in example:
```elixir
# lib/bootleg/tasks/other.ex

defmodule Bootleg.Tasks.Other do
  use Bootleg.Task do
    task :other do
      Bootleg.UI.info("World?")
    end
  end
end

```

2. I've modified bootleg's source for debug purposes - like this:
```elixir
  @spec invoke(atom) :: :ok
  def invoke(task) when is_atom(task) do
    IO.inspect("Invoking task #{inspect task}")
    invoke_task_callbacks(task, :before_hooks)

    module_name = module_for_task(task)
    IO.inspect("Module name is #{inspect module_name}")
    if Code.ensure_compiled?(module_name) do
      IO.inspect("Module is loaded")
      apply(module_name, :execute, [])
    else
      IO.inspect("Module is NOT loaded")
    end

    invoke_task_callbacks(task, :after_hooks)
  end
```

3. Now, I'm trying to call this task via invoke:

```elixir
$ mix bootleg.invoke other
"Invoking task :other"
"Module name is Bootleg.DynamicTasks.Other"
"Module is NOT loaded"
$
```

4. Calling `phoenix_digest` from bootleg_phoenix package is working:
```bash
$ mix bootleg.invoke phoenix_digest
"Invoking task :phoenix_digest"
"Module name is Bootleg.DynamicTasks.PhoenixDigest"
"Module is loaded"
....
$
```

5. The task `other` is also working via iex shell:

```elixir
iex(1)> Bootleg.Config.invoke :other
"Invoking task :other"
"Module name is Bootleg.DynamicTasks.Other"
"Module is loaded"
World?
:ok
iex(2)>
```

I'm totally missed in this reality, hope my debuggings will help you with fixing this bug.

**Comment by rjanja** [comment]
Hi @Virviil, thanks for the feedback. 

Custom tasks defined by your application will need to be located in the `deploy.exs` file. If you're creating external tasks to share with others or reuse yourself, they must be located within a `Mix.Project` dependency in order for Bootleg to be able to find and load them.

I apologize for the confusion. We'll be updating the task provider documentation to call this out more clearly.
