### ISSUE TITLE
Puzzling Internal Error

### ISSUE THREAD

**Issue by jherdman** [labzero/bootleg#204]
I'm seeing a rather puzzling and opaque internal error:

```
$ mix bootleg.build production
Creating remote context at '/tmp/bootleg/build'
[MY_BUILD_HOST] (export REPLACE_OS_VARS="true" && /usr/bin/env mkdir -p /tmp/bootleg/build)
** (SSHError) SSHKit returned an internal error on MY_BUILD_HOST: {:function_clause, [{:public_key, :pem_entry_decode, [nil], [file: 'public_key.erl', line: 141]}, {SSHClientKeyAPI, :user_key, 2, [file: 'lib/ssh_client_key_api.ex', line: 102]}, {:ssh_auth, :get_public_key, 2, [file: 'ssh_auth.erl', line: 145]}, {:ssh_connection_handler, :is_usable_user_pubkey, 2, [file: 'ssh_connection_handler.erl', line: 1769]}, {:ssh_connection_handler, :"-init_ssh_record/4-lc$^0/1-0-", 2, [file: 'ssh_connection_handler.erl', line: 477]}, {:ssh_connection_handler, :init_ssh_record, 4, [file: 'ssh_connection_handler.erl', line: 476]}, {:ssh_connection_handler, :init, 1, [file: 'ssh_connection_handler.erl', line: 412]}, {:ssh_connection_handler, :init_connection_handler, 3, [file: 'ssh_connection_handler.erl', line: 374]}]}
    lib/bootleg/ssh.ex:70: anonymous fn/2 in Bootleg.SSH.run/2
    (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
    lib/bootleg/ssh.ex:163: Bootleg.SSH.run!/2
    lib/bootleg/ssh.ex:87: Bootleg.SSH.validate_workspace/3
    lib/bootleg/ssh.ex:51: Bootleg.SSH.init/2
    lib/strategies/build/distillery.ex:9: Bootleg.Strategies.Build.Distillery.init/0
    lib/strategies/build/distillery.ex:16: Bootleg.Strategies.Build.Distillery.build/0
    lib/bootleg/config.ex:356: Bootleg.Config.invoke/1
```

I'm using and ed25519 key if that helps. This is a brand new server. Might you be able to offer some insight or means of debugging this error?

**Comment by jherdman** [comment]
Actually, yes: I can confirm that it's my ed25519 key. Is there something I'm missing to use it?

**Comment by rjanja** [comment]
Hi @jherdman, 

Thanks for the feedback. It looks like ed25519 is just not supported by Erlang :ssh, which Bootleg uses via SSHKit.ex.

A list of supported algorithms is here:
http://erlang.org/doc/man/SSH_app.html#supported

A request for additional support, including ed25519:
https://bugs.erlang.org/browse/ERL-356

Sorry there is not better news!

**Comment by holetse** [comment]
Hi jherdman, thanks for getting in touch. ED21559 is not supported by Erlang yet from what I can see. Thus the underlying SSH subsystem is blowing up on you. Bootleg does not add or extend the supported ciphers, opting to rely on what Erlang/OTP provide. You may be able to recompile Erlang/OTP to add the support with some third-party code.

**Comment by jherdman** [comment]
Ah, snap! I think it's safe to close this in the face of this news.
