### ISSUE TITLE
Configure which branch to deploy

### ISSUE THREAD

**Issue by pmeinhardt** [labzero/bootleg#212]
Hi there :wave:,

I was wondering how I could deploy a branch other than `master`?

I saw a `:refspec` option mentioned in the README, but adding that to the `role :build` did not have any effect. Am I doing something wrong?

Thanks a lot ☀️

**Comment by brienw** [comment]
You can specify it inside your deploy.exs as:
`config :refspec, "awesome_branch"`

but as you seem to have noticed, perhaps having it as a `role` option is a more intuitive place to specify this. what's your thoughts? Perhaps having this additionally as a parameter to the `bootleg.build` mix task would be a nice option

**Comment by pmeinhardt** [comment]
Ah, nice! You can read my thoughts. I was going to to ask you exactly that, because it needs to be an "environment-specific" config option 😄 

Having it as a `config` and not a `role` actually makes more sense I think.

I was just a bit disoriented because the `config` DSL was not demoed the README. Adding some simple examples of environment specific configs and the use of `config` in general to the README might be useful.

Thanks for the quick response @brienw. That's so awesome 🙏

**Comment by brienw** [comment]
I will get the docs updated with this and a few more examples today, thank you!
