### ISSUE TITLE
Creating remote context twice causes failure

### ISSUE THREAD

**Issue by snewcomer** [labzero/bootleg#240]
Version - master

From what I can tell, doing a remote build is creating the workspace, but then subsequently running it again when also trying to compile, resulting in an error.  Any thoughts where this might be coming from?

<img width="866" alt="screen shot 2018-04-27 at 11 14 44 pm" src="https://user-images.githubusercontent.com/7374640/39392822-c3819944-4a71-11e8-839d-27cb7f205a0f.png">

**Comment by snewcomer** [comment]
`role :build, "127.0.0.1", post: 2222, user: "myname", workspace: "/tmp/bootleg/build", replace_os_vars: true, silently_accept_hosts: true`

**Comment by StephaneRob** [comment]
Do you use kiex to manage elixir version ?

**Comment by brienw** [comment]
@snewcomer Were you able to get around the `stderr: /usr/bin/env: 'mix': No such file or directory` error? The "Creating remote context" message is actually referring to an internal data structure `SSHKit.Context` which is a bit confusing. I've just added #249 to remove that message. I believe your failure is happening during the `mix local.rebar` step.

I know this is like months later, sorry for the slow reply, i've been buried in other client work up until now
