### ISSUE TITLE
Erlang/OTP 21 needs Distillery >= 1.5.3

### ISSUE THREAD

**Issue by guidotripaldi** [labzero/bootleg#245]
This is not an issue directly related to the Bootleg code, but for anyone who gets an error similar to

`init terminating in do_boot ({cannot get bootfile,no_dot_erlang.boot})`

when he tries to starting/stopping/pinging a deployed app through the Bootleg commands after upgrading to Erlang/OTP 21, just upgrade Distillery to v. 1.5.3 and the problem will be resolved:

`$ mix deps.update distillery`

reference: [Distillery Issue #426](https://github.com/bitwalker/distillery/issues/426)

**Comment by brienw** [comment]
I have updated the distillery version in the README docs, too, thanks for the heads up!
