### ISSUE TITLE
Add support for password protected ssh keys.

### ISSUE THREAD

**Issue by brienw** [labzero/bootleg#251]
With the latest 0.2.0 release of [labzero/ssh_client_key_api](https://github.com/labzero/ssh_client_key_api) is can now handle password protected ssh keys. Support for these keys should now be added into Bootleg. 

I see two possible ways that we might want to allow this. One would be to allow for a configuration key to define the password to be used, the other would be to prompt the user to enter the password on-demand via the console when needed.

I would be interested in hearing peoples' thoughts on the desired implementation(s) of this, especially about the desired user experience.

@pmeinhardt @svoynow @rjanja @andreasknoepfle @johantell

**Comment by svoynow** [comment]
I don't think "interactive" use was really in the original vision, and I'm hesitant to open that door.

**Comment by rjanja** [comment]
A new config option e.g. `passphrase_provider` could be made to accept a function reference, or a string path to a binary that, when called, does some sorcery (interactive or otherwise) in order to return a passphrase that unlocks the key. This would at least keep the implementation of asking for passphrases outside of Bootleg, while still providing some support for it.

**Comment by pmeinhardt** [comment]
Nice. I love that the `ssh_client_key_api` package now supports password-protected keys 😍

Just looking at Capistrano here as an "inspiration" 🤔 A helper like `ask` could be a nice way of interactively asking a user to provide configuration values:
https://capistranorb.com/documentation/faq/how-can-i-get-capistrano-to-prompt-for-a-password/

I am not sure whether this is something that can be made to work with Bootleg's configuration approach or whether you actually want to support this. Just some food for thought 🙂
