### ISSUE TITLE
Add docs page for building in CircleCI (SSH key set-up)

### ISSUE THREAD

**Issue by tap349** [labzero/bootleg#273]
Hi!

Running `bootleg.build` Mix task on CircleCI fails with this error:

```
Starting remote build for production environment
[172.104.X.X] (export BOOTLEG_ENV="production" REPLACE_OS_VARS="true" && /usr/bin/env mkdir -p /tmp/bootleg/build)

18:37:16.444 [info]  Erlang SSH :client 4.7.1 (OpenSSL 1.1.0f  25 May 2017).
Server: 'SSH-2.0-OpenSSH_7.6p1 Ubuntu-4'
Disconnects with code = 14 [RFC4253 11.1]: Unable to connect using the available authentication methods
State = {userauth,client}
Module = ssh_connection_handler, Line = 895.
Details:
  User auth failed for: "lain"

** (SSHError) SSHKit returned an internal error on 172.104.X.X: 'Unable to connect using the available authentication methods'
    lib/bootleg/ssh.ex:99: anonymous fn/2 in Bootleg.SSH.run/2
```

If I pass `user_interaction: true` option to Bootleg role, I'm prompted to type SSH password - so it looks like SSH private key is not read from `ssh-agent`. My private SSH key was previously added to CircleCI build VM with `add_ssh_keys` step. It's all setup correctly since I can SSH into remote build host by just typing `ssh user@IP` but it fails to connect from inside `bootleg.build` task.

Also I tried to pass `identity: "~/.ssh/id_rsa"` option - this has no effect (the path is correct).

I didn't have any SSH errors with exactly the same configuration when I used edeliver - so I guess it must be all about configuring SSHKit correctly. But I'm out of ideas how to do it (

P.S. everything works on my local machine (I use SSH agent).

relevant parts of my Bootleg configs:

```elixir
# config/deploy.exs

role(:build, "<IP>", user: "lain", silently_accept_hosts: true)
```

```elixir
# config/deploy/production.exs

role(:app, "<IP>", user: "lain", silently_accept_hosts: true)
```

**Comment by rjanja** [comment]
Hi, thanks for the feedback.

`ssh-agent` isn't supported in Elixir and Erlang so even though connections work from the command line, it can be more difficult to trace down why a key isn't working. Most notably, not every type of key algorithm you may use with `ssh-agent` is supported by Erlang's `:ssh` module. I would suspect this is the case with the connection error you're seeing, that the private key is opened and read but that it's not able to be used.

Can you please verify that the key algorithm you're using is in the list here? http://erlang.org/doc/man/ssh.html#type-pubkey_alg

**Comment by tap349** [comment]
Thanks for your reply.

I'm using default RSA algorithm - `ssh_rsa` (the most common one I guess) and it's said to be supported by `:ssh` module.

As far as I understand if I specify `identity` option with a path to my private key, `ssh-agent` is no longer needed. As I wrote above, this had no effect as well (I got the same error).

I think it's important: running `mix bootleg.build` with the **same** private key and the **same** Bootleg configuration (same host, same user) works on my local machine but doesn't work in CircleCI build VM. The only difference I see is in operating systems: I'm running macOS, while CircleCI is using Linux (Ubuntu)...

**Comment by svoynow** [comment]
Can you try it with an absolute path for the `identity` option rather than using the `~`? Just to eliminate one possible variable...
And I take it that you've run the CircleCI build, `ssh`-ed to the container and confirmed that the key is where we think it is?

**Comment by tap349** [comment]
> Can you try it with an absolute path for the `identity` option rather than using the `~`? Just to eliminate one possible variable...

Yes, I tried absolute path - the same result.

> And I take it that you've run the CircleCI build, `ssh`-ed to the container and confirmed that the key is where we think it is?

Yes and not once )

Anyway I found the solution. It has turned out that Erlang`s `:ssh` module ignores not only `ssh-agent` but SSH config (`~/.ssh/config`) as well:

```sh
$ ls -l ~/.ssh | grep id_rsa
id_rsa <- default CircleCI key
id_rsa_21cd07a3b8b91f20b0eb59c7e314fc5e <- my private key
```

SSH config created by CircleCI:

```
Host 172.104.X.X
    IdentitiesOnly yes
    IdentityFile /home/circleci/.ssh/id_rsa_21cd07a3b8b91f20b0eb59c7e314fc5e
```

So SSH config correctly points to my private SSH key but `:ssh` module ignores this config and still looks for `~/.ssh/id_rsa` (which is a default CircleCI key) - so `:ssh` module is using a wrong key. That is why authentication fails.

As a workaround I added this command to my CircleCI config:

```diff
     - add_ssh_keys:
         fingerprints:
           - '21:cd:...'

+    - run: mv ~/.ssh/id_rsa_* ~/.ssh/id_rsa
```

Now everything works as expected!

P.S. I've found `key_cb_private` option - maybe it should be used to pass custom private key path (instead of `key_cb` option that is currently used by Bootleg `identify` option)?
